`nn` is the neural network module in PyTorch, providing building blocks for creating and training deep learning models.




In [2]:
import torch 

from torch import nn 


from matplotlib import pyplot as plt 


In [8]:
# Generating data - Define ground truth for Linear Regression 

weight = 0.7   # Slope parameter 
bias = 0.3   # Intercept parameter 


# Generate Sysnthetic data with known parameters (weight and bias) 
start = 0 
end = 1
step = 0.02 

X = torch.arange(start, end, step)  # Shape: (50,)
display("Tensor X (When unsqueeze is not used):", X, X.shape)

X = torch.arange(start, end, step).unsqueeze(dim=1)  # Shape: (50, 1)
# here unsqueeze is used to add an extra dimension to the tensor, making it a 2D tensor with shape (50, 1) instead of a 1D tensor with shape (50,). This is often done to ensure that the data is in the correct format for certain operations, such as matrix multiplication or when feeding it into a neural network.
display("Tensor X:", X, X.shape)

y = weight * X + bias  
display("Tensor y:", y, y.shape)


print(f"X shape: {X.shape} | y shape: {y.shape}")       


'Tensor X (When unsqueeze is not used):'

tensor([0.0000, 0.0200, 0.0400, 0.0600, 0.0800, 0.1000, 0.1200, 0.1400, 0.1600,
        0.1800, 0.2000, 0.2200, 0.2400, 0.2600, 0.2800, 0.3000, 0.3200, 0.3400,
        0.3600, 0.3800, 0.4000, 0.4200, 0.4400, 0.4600, 0.4800, 0.5000, 0.5200,
        0.5400, 0.5600, 0.5800, 0.6000, 0.6200, 0.6400, 0.6600, 0.6800, 0.7000,
        0.7200, 0.7400, 0.7600, 0.7800, 0.8000, 0.8200, 0.8400, 0.8600, 0.8800,
        0.9000, 0.9200, 0.9400, 0.9600, 0.9800])

torch.Size([50])

'Tensor X:'

tensor([[0.0000],
        [0.0200],
        [0.0400],
        [0.0600],
        [0.0800],
        [0.1000],
        [0.1200],
        [0.1400],
        [0.1600],
        [0.1800],
        [0.2000],
        [0.2200],
        [0.2400],
        [0.2600],
        [0.2800],
        [0.3000],
        [0.3200],
        [0.3400],
        [0.3600],
        [0.3800],
        [0.4000],
        [0.4200],
        [0.4400],
        [0.4600],
        [0.4800],
        [0.5000],
        [0.5200],
        [0.5400],
        [0.5600],
        [0.5800],
        [0.6000],
        [0.6200],
        [0.6400],
        [0.6600],
        [0.6800],
        [0.7000],
        [0.7200],
        [0.7400],
        [0.7600],
        [0.7800],
        [0.8000],
        [0.8200],
        [0.8400],
        [0.8600],
        [0.8800],
        [0.9000],
        [0.9200],
        [0.9400],
        [0.9600],
        [0.9800]])

torch.Size([50, 1])

'Tensor y:'

tensor([[0.3000],
        [0.3140],
        [0.3280],
        [0.3420],
        [0.3560],
        [0.3700],
        [0.3840],
        [0.3980],
        [0.4120],
        [0.4260],
        [0.4400],
        [0.4540],
        [0.4680],
        [0.4820],
        [0.4960],
        [0.5100],
        [0.5240],
        [0.5380],
        [0.5520],
        [0.5660],
        [0.5800],
        [0.5940],
        [0.6080],
        [0.6220],
        [0.6360],
        [0.6500],
        [0.6640],
        [0.6780],
        [0.6920],
        [0.7060],
        [0.7200],
        [0.7340],
        [0.7480],
        [0.7620],
        [0.7760],
        [0.7900],
        [0.8040],
        [0.8180],
        [0.8320],
        [0.8460],
        [0.8600],
        [0.8740],
        [0.8880],
        [0.9020],
        [0.9160],
        [0.9300],
        [0.9440],
        [0.9580],
        [0.9720],
        [0.9860]])

torch.Size([50, 1])

X shape: torch.Size([50, 1]) | y shape: torch.Size([50, 1])


In [9]:
# 

train_split = int(0.8 * len(X))  # 80% for training, 20% for testing

# 
X_train, y_train = X[:train_split], y[:train_split]  

#    
X_test, y_test = X[train_split:], y[train_split:]


# Final check of the data 
print(f"X_train shape: {X_train.shape} | y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape} | y_test shape: {y_test.shape}") 



X_train shape: torch.Size([40, 1]) | y_train shape: torch.Size([40, 1])
X_test shape: torch.Size([10, 1]) | y_test shape: torch.Size([10, 1])
